language: node_js

node_js:
  - node 

jdk:
  - oraclejdk8 

services: 
  - mysql

addons: 
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

notifications:
  email: false

branches:
  only:
    - master

before_script:
  - mysql -e 'CREATE DATABASE MAGAZINE;'
  - mysql -e 'USE MAGAZINE';
  
script:
  - cd backend
  - npm install
  - npm run migration:create
  - npm run migration:run
  - npm run test
  - cd ../frontend
  - npm install
  - ng lint
  - ng build --prod